version: "3"
services:
    frontend:
        image: node:lts-alpine
        restart: always
        working_dir: /home/node/app
        volumes:
            - .:/home/node/app
        command: sh -c "npm i && npm run build && node ./build/index.js"
        ports:
            - "80:3000"
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
